const mongoose = require("mongoose");
const random = require('mongoose-simple-random');

const QuestionSchema = new mongoose.Schema({
  creator_id: String,
  date: Date,
  questionLocation: {
     type: { type: String },
     coordinates: [],
    },
  question: String, // links to the _id of a parent story (_id is an autogenerated field by Mongoose).
  answers: [],
  freeResponseAnswers: [],
  allowFreeResponse: Boolean
});
QuestionSchema.index({ questionLocation: "2dsphere" });
QuestionSchema.plugin(random)
// compile model from schema
module.exports = mongoose.model("question", QuestionSchema);
